2014-02-09 18:43:30+0800 [scrapy] INFO: Scrapy 0.22.0 started (bot: taobao)
2014-02-09 18:43:30+0800 [scrapy] INFO: Optional features available: ssl, http11
2014-02-09 18:43:30+0800 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'taobao.spiders', 'SPIDER_MODULES': ['taobao.spiders'], 'LOG_LEVEL': 'INFO', 'BOT_NAME': 'taobao'}
2014-02-09 18:43:30+0800 [scrapy] INFO: Enabled extensions: LogStats, TelnetConsole, CloseSpider, WebService, CoreStats, SpiderState
2014-02-09 18:43:30+0800 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2014-02-09 18:43:30+0800 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2014-02-09 18:43:30+0800 [scrapy] INFO: Enabled item pipelines: SellerPipeline
2014-02-09 18:43:30+0800 [taobao] INFO: Spider opened
2014-02-09 18:43:30+0800 [taobao] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
No handlers could be found for logger "peewee"
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 35338216935L,
	 'flag': 'Seller',
	 'name': u'\u65e0\u9645\u9ea6\u7530\u901a\u8baf',
	 'positiveFeedbackRate': 98.96,
	 'reputScore': 2001,
	 'sellerId': 376799512,
	 'shopDesc': [4.8, 4.8, 4.8]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.IntegrityError: null value in column "commId" violates not-null constraint
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 27610584433L,
	 'flag': 'Seller',
	 'name': u'\u4e09\u4f1f\u7d22\u7231\u79d1\u6280',
	 'positiveFeedbackRate': 99.45,
	 'reputScore': 20001,
	 'sellerId': 380624657,
	 'shopDesc': [4.8, 4.8, 4.8]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 27231920382L,
	 'flag': 'Seller',
	 'name': u'haijian52088',
	 'positiveFeedbackRate': 99.59,
	 'reputScore': 200001,
	 'sellerId': 13363864,
	 'shopDesc': [4.8, 4.8, 4.7]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 20098897075L,
	 'flag': 'Seller',
	 'name': u'\u6700\u4f4e\u6700\u8bda\u4fe1',
	 'positiveFeedbackRate': 99.86,
	 'reputScore': 100001,
	 'sellerId': 12573474,
	 'shopDesc': [4.8, 4.8, 4.8]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 21894319337L,
	 'flag': 'Seller',
	 'name': u'\u975e\u5e38\u624b\u673a',
	 'positiveFeedbackRate': 99.61,
	 'reputScore': 500001,
	 'sellerId': 853982,
	 'shopDesc': [4.7, 4.7, 4.7]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 20128886326L,
	 'flag': 'Seller',
	 'name': u'\u65b0\u592a\u6570\u7801\u901a\u8baf',
	 'positiveFeedbackRate': 99.2,
	 'reputScore': 50001,
	 'sellerId': 183262695,
	 'shopDesc': [4.7, 4.6, 4.6]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 19904928406L,
	 'flag': 'Seller',
	 'name': u'\u53ea\u6709\u4e3a\u4f60123456',
	 'positiveFeedbackRate': 99.92,
	 'reputScore': 2001,
	 'sellerId': 118130847,
	 'shopDesc': [4.9, 4.9, 4.9]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 19974242521L,
	 'flag': 'Seller',
	 'name': u'gamenan',
	 'positiveFeedbackRate': 99.8,
	 'reputScore': 20001,
	 'sellerId': 196118321,
	 'shopDesc': [4.8, 4.8, 4.8]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 20152334720L,
	 'flag': 'Seller',
	 'name': u'\u9038\u67ab66',
	 'positiveFeedbackRate': 99.64,
	 'reputScore': 10001,
	 'sellerId': 37830682,
	 'shopDesc': [4.8, 4.8, 4.8]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 35239877266L,
	 'flag': 'Seller',
	 'name': u'\u8349\u6837\u5e74\u534e37',
	 'positiveFeedbackRate': 99.67,
	 'reputScore': 2001,
	 'sellerId': 688690474,
	 'shopDesc': [4.9, 4.9, 4.9]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 22577235117L,
	 'flag': 'Seller',
	 'name': u'\u84dd\u6d77\u5c0fc',
	 'positiveFeedbackRate': 0.0,
	 'reputScore': 1001,
	 'sellerId': 477135813,
	 'shopDesc': [4.8, 4.8, 4.8]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 20234961703L,
	 'flag': 'Seller',
	 'name': u'yulicun888',
	 'positiveFeedbackRate': 99.42,
	 'reputScore': 20001,
	 'sellerId': 141757951,
	 'shopDesc': [4.8, 4.8, 4.8]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 36219663328L,
	 'flag': 'Seller',
	 'name': u'yzjjsl168',
	 'positiveFeedbackRate': 99.07,
	 'reputScore': 2001,
	 'sellerId': 47352879,
	 'shopDesc': [4.7, 4.7, 4.8]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 36282039921L,
	 'flag': 'Seller',
	 'name': u'\u5357\u6ce2\u4e071',
	 'positiveFeedbackRate': 99.81,
	 'reputScore': 5001,
	 'sellerId': 37213332,
	 'shopDesc': [4.9, 4.8, 4.9]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 20285310137L,
	 'flag': 'Seller',
	 'name': u'\u542f\u6cf0\u6570\u7801',
	 'positiveFeedbackRate': 99.1,
	 'reputScore': 50001,
	 'sellerId': 387784786,
	 'shopDesc': [4.8, 4.8, 4.8]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 35097573089L,
	 'flag': 'Seller',
	 'name': u'\u6dc5\u6c5f\u5546\u53f7',
	 'positiveFeedbackRate': 99.9,
	 'reputScore': 10001,
	 'sellerId': 280003475,
	 'shopDesc': [4.9, 4.8, 4.9]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 20207569618L,
	 'flag': 'Seller',
	 'name': u'yyxming',
	 'positiveFeedbackRate': 99.25,
	 'reputScore': 10001,
	 'sellerId': 441017263,
	 'shopDesc': [4.8, 4.8, 4.8]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 20024530272L,
	 'flag': 'Seller',
	 'name': u'\u9999\u6e2f\u9ad8\u767b',
	 'positiveFeedbackRate': 99.9,
	 'reputScore': 5001,
	 'sellerId': 71011031,
	 'shopDesc': [4.9, 4.9, 4.9]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 35251170624L,
	 'flag': 'Seller',
	 'name': u'\u9b54\u529b\u901a\u8baf',
	 'positiveFeedbackRate': 99.78,
	 'reputScore': 20001,
	 'sellerId': 214498135,
	 'shopDesc': [4.8, 4.8, 4.8]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 20308334886L,
	 'flag': 'Seller',
	 'name': u'\u5c0f\u745e\u4ed4',
	 'positiveFeedbackRate': 99.56,
	 'reputScore': 20001,
	 'sellerId': 48788909,
	 'shopDesc': [4.9, 4.9, 4.9]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 20099094566L,
	 'flag': 'Seller',
	 'name': u'ygsd',
	 'positiveFeedbackRate': 99.63,
	 'reputScore': 50001,
	 'sellerId': 898225,
	 'shopDesc': [4.8, 4.8, 4.8]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 20144697863L,
	 'flag': 'Seller',
	 'name': u'\u6717\u6717\u7535\u73a9',
	 'positiveFeedbackRate': 99.68,
	 'reputScore': 20001,
	 'sellerId': 129307262,
	 'shopDesc': [4.8, 4.8, 4.9]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 36901005570L,
	 'flag': 'Seller',
	 'name': u'sweety_\u679c\u513f',
	 'positiveFeedbackRate': 97.1,
	 'reputScore': 251,
	 'sellerId': 341621047,
	 'shopDesc': [4.9, 4.9, 4.9]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 22453171081L,
	 'flag': 'Seller',
	 'name': u'\u9633\u5149\u6570\u7801\u6e2f',
	 'positiveFeedbackRate': 99.88,
	 'reputScore': 2001,
	 'sellerId': 1230765,
	 'shopDesc': [4.9, 4.9, 4.9]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 22586983019L,
	 'flag': 'Seller',
	 'name': u'zxsgtc',
	 'positiveFeedbackRate': 99.65,
	 'reputScore': 20001,
	 'sellerId': 11247811,
	 'shopDesc': [4.9, 4.9, 4.9]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 36690575985L,
	 'flag': 'Seller',
	 'name': u'hzy_ck',
	 'positiveFeedbackRate': 99.92,
	 'reputScore': 10001,
	 'sellerId': 549140155,
	 'shopDesc': [4.9, 4.9, 4.9]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 20153906339L,
	 'flag': 'Seller',
	 'name': u'\u7433\u7433_shop',
	 'positiveFeedbackRate': 99.76,
	 'reputScore': 10001,
	 'sellerId': 240867039,
	 'shopDesc': [4.7, 4.7, 4.6]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 20265126573L,
	 'flag': 'Seller',
	 'name': u'\u4e5d\u5dde\u7535\u566888',
	 'positiveFeedbackRate': 99.65,
	 'reputScore': 1001,
	 'sellerId': 684101364,
	 'shopDesc': [4.8, 4.8, 4.9]}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 22, in process_item
	    seller.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 35338216935L,
	 'flag': 'Commodity',
	 'rateNumber': 329,
	 'sellerId': 376799512,
	 'title': u'\u539f\u5c01\u672a\u6fc0\u6d3bApple/\u82f9\u679c iPhone 5\u4ee3 \u5168\u65b0\u65e0\u9501 \u4e24\u7f51\u4e09\u7f51\u7535\u4fe13G\u624b\u673a',
	 'turnover': 231}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 27610584433L,
	 'flag': 'Commodity',
	 'rateNumber': 14850,
	 'sellerId': 380624657,
	 'title': u'\u5a01\u950b\u8ba4\u8bc1 \u6b63\u54c1\u4fdd\u969c \u5f53\u5929\u53d1\u8d27 Apple/\u82f9\u679c iPhone 5S \u6b63\u6e2f v\u7248\u4e09\u7f51',
	 'turnover': 7027}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 27231920382L,
	 'flag': 'Commodity',
	 'rateNumber': 6696,
	 'sellerId': 13363864,
	 'title': u'\u95ea\u7535\u53d1\u8d27 \u9001\u5f69\u7968\u2605\u7279\u4ef7\u6e2f\u7248\u539f\u5c01\u672a\u6fc0\u6d3bV\u4e09\u7f51Apple/\u82f9\u679c iPhone 5S',
	 'turnover': 3757}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 20098897075L,
	 'flag': 'Commodity',
	 'rateNumber': 6493,
	 'sellerId': 12573474,
	 'title': u'Apple/\u82f9\u679c iPhone 5S\u82f9\u679c5S \u4e09\u7f51V\u7248 \u6e2f\u7248\u672a\u6fc0\u6d3b\u3010\u6625\u8282\u4e0d\u6253\u70ca\u3011',
	 'turnover': 2860}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 21894319337L,
	 'flag': 'Commodity',
	 'rateNumber': 6342,
	 'sellerId': 853982,
	 'title': u'\u3010\u60c5\u4eba\u8282\u7279\u4ef7\u3011Apple/\u82f9\u679c iPhone 5S\u82f9\u679c5s \u79fb\u52a84G\u7248 \u4e09\u7f51\u7535\u4fe1\u7248',
	 'turnover': 3697}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 20128886326L,
	 'flag': 'Commodity',
	 'rateNumber': 2298,
	 'sellerId': 183262695,
	 'title': u'\u3010\u571f\u8c6a\u91d1\u7279\u4ef7.4120\u3011Apple/\u82f9\u679c iPhone 5S \u82f9\u679c5S \u6e2f\u7248 \u4e09\u7f51V\u7248',
	 'turnover': 2265}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 19904928406L,
	 'flag': 'Commodity',
	 'rateNumber': 467,
	 'sellerId': 118130847,
	 'title': u'Apple/\u82f9\u679c iPhone 5S\u6e2f\u7248 \u5168\u65b0\u9999\u6e2f\u5b98\u7f51\u4ee3\u8d2d\u539f\u5c01\u725b\u76ae\u7eb8\u76d2\u5e26\u7968',
	 'turnover': 495}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 19974242521L,
	 'flag': 'Commodity',
	 'rateNumber': 5332,
	 'sellerId': 196118321,
	 'title': u'\u3010\u9650\u65f6\u9001\u94a2\u5316\u9632\u7206\u819c \u6e2f\u7248\u571f\u8c6a\u91d14278\u3011Apple/\u82f9\u679c iPhone 5S \u56fd\u884c',
	 'turnover': 1120}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 20152334720L,
	 'flag': 'Commodity',
	 'rateNumber': 2087,
	 'sellerId': 37830682,
	 'title': u'Apple/\u82f9\u679c iPhone 5S 16G\u4e09\u7f51\u901aV\u7248\u539f\u5c01\u6e2f\u884c\u571f\u8c6a\u91d1 \u9ed1\u767d\u82724168',
	 'turnover': 1218}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 35239877266L,
	 'flag': 'Commodity',
	 'rateNumber': 279,
	 'sellerId': 688690474,
	 'title': u'Apple/\u82f9\u679c iPhone 5S\u6e2f\u7248 V\u7248\u4e09\u7f51 \u91d1\u8272\u4e00\u697c\u571f\u6728\u4eba \u6b63\u54c1\u5305\u90ae',
	 'turnover': 337}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 22577235117L,
	 'flag': 'Commodity',
	 'rateNumber': 609,
	 'sellerId': 477135813,
	 'title': u'Apple/\u82f9\u679c iPhone 5S\u82f9\u679c5s \u6e2f\u7248\u539f\u5c01 \u6fb3\u7248V\u7248\u4e09\u7f51  \u539f\u5c01\u91d14310',
	 'turnover': 495}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 20234961703L,
	 'flag': 'Commodity',
	 'rateNumber': 1923,
	 'sellerId': 141757951,
	 'title': u'\u5047\u4e00\u8d54\u4e07Apple/\u82f9\u679c iPhone5s \u82f9\u679c5S\u624b\u673a \u65e5\u7248\u7f8e\u7248 \u9001\u7ea2\u5305\u8fce\u65b0\u5e74',
	 'turnover': 759}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 36219663328L,
	 'flag': 'Commodity',
	 'rateNumber': 175,
	 'sellerId': 47352879,
	 'title': u'\u6625\u8282\u4e0d\u6253\u70ca Apple/\u82f9\u679c iPhone 5s(\u6709\u9501) \u82f9\u679c5s \u65e5\u7248 \u7f8e\u7248\u571f\u8c6a\u91d1',
	 'turnover': 265}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 36282039921L,
	 'flag': 'Commodity',
	 'rateNumber': 400,
	 'sellerId': 37213332,
	 'title': u'Apple/\u82f9\u679c iPhone 5S \u82f9\u679c5S 16G 32G 64 \u79fb\u52a8\u8054\u901a\u7f8e\u7248\u65e0\u9501\u6b63\u54c1',
	 'turnover': 542}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 20285310137L,
	 'flag': 'Commodity',
	 'rateNumber': 376,
	 'sellerId': 387784786,
	 'title': u'Apple/\u82f9\u679c iPhone 5S \u6e2f\u72483G 4G  iPhone 5S V\u7248\u4e09\u7f51 \u73b0\u8d27\u5305\u90ae',
	 'turnover': 522}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 35097573089L,
	 'flag': 'Commodity',
	 'rateNumber': 455,
	 'sellerId': 280003475,
	 'title': u'Apple/\u82f9\u679c iPhone 5S \u82f9\u679c5S \u6e2f\u7248\u539f\u5c01\u672a\u6fc0\u6d3b \u4e09\u7f51\u7248\u7535\u4fe1 \u9a6c\u4e0a\u53d1',
	 'turnover': 193}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 20207569618L,
	 'flag': 'Commodity',
	 'rateNumber': 1309,
	 'sellerId': 441017263,
	 'title': u'\u3010\u6b63\u5f0f\u4e0a\u73ed \u5f53\u5929\u53d1\u8d27\u3011Apple/\u82f9\u679c iPhone 5S v\u7248 \u4e09\u7f51 \u7535\u4fe1 \u6e2f\u7248',
	 'turnover': 788}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 20024530272L,
	 'flag': 'Commodity',
	 'rateNumber': 1297,
	 'sellerId': 71011031,
	 'title': u'Apple/\u82f9\u679c iPhone 5S \u9999\u6e2f\u5546\u5bb6 \u539f\u5c01\u672a\u6fc0\u6d3b\u5305\u90ae \u767e\u5206\u767e\u539f\u88c5 \u72c2\u4fc3',
	 'turnover': 599}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 35251170624L,
	 'flag': 'Commodity',
	 'rateNumber': 1429,
	 'sellerId': 214498135,
	 'title': u'\u5047\u4e00\u8d54\u4e07Apple/\u82f9\u679c iPhone 5s \u82f9\u679c5S\u624b\u673a \u65e5\u7248 \u7f8e\u7248 \u7ea2\u5305\u8fce\u65b0\u5e74',
	 'turnover': 562}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 20308334886L,
	 'flag': 'Commodity',
	 'rateNumber': 430,
	 'sellerId': 48788909,
	 'title': u'\u7a46\u4e30\u25c6Apple/\u82f9\u679c iPhone 5S \u672a\u6fc0\u6d3b iPhone5s \u79fb\u52a84G\u571f\u8c6a\u91d1A1530',
	 'turnover': 547}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 20099094566L,
	 'flag': 'Commodity',
	 'rateNumber': 2468,
	 'sellerId': 898225,
	 'title': u'[\u539f\u5c01\u672a\u6fc0\u6d3b \u571f\u8c6a\u91d14188]Apple/\u82f9\u679c iPhone 5S\u82f9\u679c5S\u4e09\u7f51V\u7248\u6e2f\u7248',
	 'turnover': 1110}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 20144697863L,
	 'flag': 'Commodity',
	 'rateNumber': 687,
	 'sellerId': 129307262,
	 'title': u'\u65b0\u5e74\u7279\u4ef7Apple/\u82f9\u679c iPhone 5S \u56fd\u884c/\u6e2f\u7248A1530\u652f\u6301\u79fb\u52a84G\u5305\u90ae',
	 'turnover': 712}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 36901005570L,
	 'flag': 'Commodity',
	 'rateNumber': 64,
	 'sellerId': 341621047,
	 'title': u'\u3010\u5a01\u950b\u8ba4\u8bc1\u3011Apple/\u82f9\u679c iPhone 5S 16G \u56fd\u884c\u6e2f\u7248 \u672a\u6fc0\u6d3b \u5b8c\u7f8e4G',
	 'turnover': 277}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 22453171081L,
	 'flag': 'Commodity',
	 'rateNumber': 134,
	 'sellerId': 1230765,
	 'title': u'Apple/\u82f9\u679c iPhone 5s \u5b8c\u7f8e\u8d8a\u72f1\u65e5\u7248\u7f8e\u7248AU/SB att \u6625\u8282\u53d1\u8d27',
	 'turnover': 143}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 22586983019L,
	 'flag': 'Commodity',
	 'rateNumber': 533,
	 'sellerId': 11247811,
	 'title': u'Apple/\u82f9\u679c iPhone 5S \u82f9\u679c5S \u4ee3\u8d2d iPhone5S A1530 \u6e2f\u7248 \u672a\u6fc0\u6d3b',
	 'turnover': 444}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 36690575985L,
	 'flag': 'Commodity',
	 'rateNumber': 1021,
	 'sellerId': 549140155,
	 'title': u'Apple/\u82f9\u679c iPhone 5 \u539f\u88c5\u6b63\u54c1 V\u7248 \u4e09\u7f51\u7535\u4fe1 \u672a\u6fc0\u6d3b \u5f53\u5929\u53d1\u8d27',
	 'turnover': 762}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 20153906339L,
	 'flag': 'Commodity',
	 'rateNumber': 204,
	 'sellerId': 240867039,
	 'title': u'Apple/\u82f9\u679c iPhone 5s \u82f9\u679c5S \u624b\u673a \u539f\u88c5\u6b63\u54c1 \u539f\u88c5\u672a\u62c6\u5c01',
	 'turnover': 129}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] ERROR: Error processing {'commId': 20265126573L,
	 'flag': 'Commodity',
	 'rateNumber': 4,
	 'sellerId': 684101364,
	 'title': u'Apple/\u82f9\u679c iPhone 5s 5C\u3010\u6e2f\u7248\u8054\u4fdd\u7279\u4ef7\u70ed\u9500\u3011\u624b\u673a\u516c\u56ed\u5f90\u5bb6\u6c47',
	 'turnover': 7}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/zq/Project/taobao/taobao/pipelines.py", line 30, in process_item
	    commodity.save()
	  File "build/bdist.linux-i686/egg/peewee.py", line 2910, in save
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2068, in execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 1698, in _execute
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2232, in execute_sql
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2104, in __exit__
	    
	  File "build/bdist.linux-i686/egg/peewee.py", line 2223, in execute_sql
	    
	peewee.InternalError: current transaction is aborted, commands ignored until end of transaction block
	
	
2014-02-09 18:43:30+0800 [taobao] INFO: Closing spider (finished)
2014-02-09 18:43:30+0800 [taobao] INFO: Dumping Scrapy stats:
	{'downloader/request_bytes': 573,
	 'downloader/request_count': 2,
	 'downloader/request_method_count/GET': 2,
	 'downloader/response_bytes': 44085,
	 'downloader/response_count': 2,
	 'downloader/response_status_count/200': 2,
	 'finish_reason': 'finished',
	 'finish_time': datetime.datetime(2014, 2, 9, 10, 43, 30, 959035),
	 'log_count/ERROR': 56,
	 'log_count/INFO': 7,
	 'request_depth_max': 1,
	 'response_received_count': 2,
	 'scheduler/dequeued': 2,
	 'scheduler/dequeued/memory': 2,
	 'scheduler/enqueued': 2,
	 'scheduler/enqueued/memory': 2,
	 'start_time': datetime.datetime(2014, 2, 9, 10, 43, 30, 553776)}
2014-02-09 18:43:30+0800 [taobao] INFO: Spider closed (finished)
